;;; doom-rose-pine-common.el --- Shared spec for Rosé Pine themes -*- lexical-binding: t; no-byte-compile: t; -*-
;;
;; Author: tamnd
;; Keywords: faces, custom themes
;; Homepage: https://github.com/tamnd/rose-pine-doom-emacs
;; Package-Requires: ((emacs "27.1") (doom-themes "2.2.1"))
;;
;;; Commentary:
;;
;; Shared defcustoms and face spec for the three Rosé Pine variants:
;; `doom-rose-pine', `doom-rose-pine-moon', `doom-rose-pine-dawn'.
;;
;; The variants only differ in their palette.  Every face override is
;; written against the palette role names (rose, gold, foam, pine,
;; iris, love, text, subtle, muted, base, surface, overlay,
;; highlight-low, highlight-med, highlight-high) so a single face spec
;; works for all three.
;;
;;; Code:

(require 'doom-themes)

(defgroup doom-rose-pine nil
  "Options shared by the Rosé Pine theme variants."
  :group 'doom-themes)

(defcustom doom-rose-pine-brighter-modeline nil
  "If non-nil, use a more vivid mode-line background.
Applies to all three Rosé Pine variants."
  :group 'doom-rose-pine
  :type 'boolean)

(defcustom doom-rose-pine-brighter-comments nil
  "If non-nil, draw comments with a subtle tinted background."
  :group 'doom-rose-pine
  :type 'boolean)

(defcustom doom-rose-pine-padded-modeline doom-themes-padded-modeline
  "If non-nil, add padding to the mode-line.
Either a boolean (4-pixel default) or an integer pixel width."
  :group 'doom-rose-pine
  :type '(choice integer boolean))

;; Backwards-compatible aliases for the per-variant custom names used
;; by the original donniebreve port.  Setting any of these continues
;; to work — they all forward to the unified options above.
(define-obsolete-variable-alias 'doom-rose-pine-moon-brighter-modeline
  'doom-rose-pine-brighter-modeline "1.0.0")
(define-obsolete-variable-alias 'doom-rose-pine-moon-brighter-comments
  'doom-rose-pine-brighter-comments "1.0.0")
(define-obsolete-variable-alias 'doom-rose-pine-moon-padded-modeline
  'doom-rose-pine-padded-modeline "1.0.0")
(define-obsolete-variable-alias 'doom-rose-pine-dawn-brighter-modeline
  'doom-rose-pine-brighter-modeline "1.0.0")
(define-obsolete-variable-alias 'doom-rose-pine-dawn-brighter-comments
  'doom-rose-pine-brighter-comments "1.0.0")
(define-obsolete-variable-alias 'doom-rose-pine-dawn-padded-modeline
  'doom-rose-pine-padded-modeline "1.0.0")

(defconst doom-rose-pine--face-spec
  '(;; --- core editor ---
    ((font-lock-comment-face &override)
     :slant 'italic
     :background (if doom-rose-pine-brighter-comments (doom-blend foam base 0.07)))
    ((font-lock-doc-face &override) :slant 'italic)
    ((font-lock-type-face &override) :foreground type :slant 'italic)
    ((font-lock-builtin-face &override) :foreground builtin :slant 'italic)
    ((font-lock-function-name-face &override) :foreground functions)
    ((font-lock-variable-name-face &override) :foreground variables)
    ((font-lock-keyword-face &override) :foreground keywords :weight 'bold)
    ((font-lock-constant-face &override) :foreground constants :weight 'bold)
    ((font-lock-number-face &override) :foreground numbers)
    ((font-lock-string-face &override) :foreground strings)
    ((font-lock-operator-face &override) :foreground operators)
    ((font-lock-punctuation-face &override) :foreground subtle)
    ((font-lock-bracket-face &override) :foreground subtle)
    ((font-lock-delimiter-face &override) :foreground subtle)
    ((font-lock-property-name-face &override) :foreground text)
    ((font-lock-property-use-face &override) :foreground text)
    ((font-lock-preprocessor-face &override) :foreground iris)
    ((font-lock-warning-face &override) :foreground gold :weight 'bold)

    (cursor :background highlight)
    (hl-line :background highlight-low)
    ((line-number &override) :foreground muted)
    ((line-number-current-line &override) :foreground rose :weight 'bold)
    (fringe :foreground muted :background bg)
    (vertical-border :foreground overlay :background bg)
    (link :foreground foam :underline t)
    (highlight :foreground base :background rose)
    (lazy-highlight :background highlight-med :foreground text)
    (isearch :background gold :foreground base :weight 'bold)
    (isearch-fail :background love :foreground base)
    (match :foreground gold :weight 'bold)
    (success :foreground foam)
    (warning :foreground gold)
    (error   :foreground love)
    (escape-glyph :foreground iris)
    (homoglyph    :foreground iris)
    ((show-paren-match &override)
     :foreground rose :background highlight-high :weight 'bold)
    ((show-paren-mismatch &override)
     :foreground base :background love :weight 'bold)
    (trailing-whitespace :background love)
    ((whitespace-tab &override) :foreground highlight-high :background nil)
    ((whitespace-space &override) :foreground highlight-high :background nil)
    ((whitespace-newline &override) :foreground highlight-high :background nil)
    ((whitespace-trailing &override) :foreground love :background nil)
    (header-line :background surface :foreground subtle)
    (mode-line
     :background modeline-bg :foreground modeline-fg
     :box (if modeline-pad `(:line-width ,modeline-pad :color ,modeline-bg)))
    (mode-line-inactive
     :background modeline-bg-inactive :foreground modeline-fg-inactive
     :box (if modeline-pad `(:line-width ,modeline-pad :color ,modeline-bg-inactive)))
    (mode-line-emphasis :foreground (if doom-rose-pine-brighter-modeline text subtle))
    (mode-line-highlight :foreground rose :weight 'bold)
    (mode-line-buffer-id :foreground text :weight 'bold)
    ((minibuffer-prompt &override) :foreground iris :weight 'bold)

    ;; --- tree-sitter / treesit-font-lock ---
    (tree-sitter-hl-face:attribute       :inherit 'font-lock-constant-face)
    (tree-sitter-hl-face:constant        :foreground constants :weight 'bold)
    (tree-sitter-hl-face:constant.builtin :foreground gold :weight 'bold)
    (tree-sitter-hl-face:number          :foreground numbers)
    (tree-sitter-hl-face:comment         :inherit 'font-lock-comment-face)
    (tree-sitter-hl-face:doc             :inherit 'font-lock-doc-face)
    (tree-sitter-hl-face:string          :foreground strings)
    (tree-sitter-hl-face:string.special  :foreground rose)
    (tree-sitter-hl-face:escape          :foreground iris)
    (tree-sitter-hl-face:type            :foreground type :slant 'italic)
    (tree-sitter-hl-face:type.parameter  :foreground iris :slant 'italic)
    (tree-sitter-hl-face:type.argument   :foreground iris)
    (tree-sitter-hl-face:type.builtin    :foreground love :slant 'italic)
    (tree-sitter-hl-face:type.super      :foreground foam :slant 'italic)
    (tree-sitter-hl-face:constructor     :foreground rose)
    (tree-sitter-hl-face:variable        :foreground variables)
    (tree-sitter-hl-face:variable.parameter :foreground iris)
    (tree-sitter-hl-face:variable.builtin :foreground love :slant 'italic)
    (tree-sitter-hl-face:variable.special :foreground rose)
    (tree-sitter-hl-face:property        :foreground text)
    (tree-sitter-hl-face:property.definition :foreground text :weight 'bold)
    (tree-sitter-hl-face:function        :foreground functions)
    (tree-sitter-hl-face:function.call   :foreground functions)
    (tree-sitter-hl-face:function.builtin :foreground love :slant 'italic)
    (tree-sitter-hl-face:function.special :foreground iris)
    (tree-sitter-hl-face:function.macro  :foreground iris)
    (tree-sitter-hl-face:method          :foreground methods)
    (tree-sitter-hl-face:method.call     :foreground methods)
    (tree-sitter-hl-face:keyword         :foreground keywords :weight 'bold)
    (tree-sitter-hl-face:operator        :foreground operators)
    (tree-sitter-hl-face:punctuation     :foreground subtle)
    (tree-sitter-hl-face:punctuation.bracket :foreground subtle)
    (tree-sitter-hl-face:punctuation.delimiter :foreground subtle)
    (tree-sitter-hl-face:punctuation.special :foreground iris)
    (tree-sitter-hl-face:tag             :foreground foam)
    (tree-sitter-hl-face:label           :foreground iris)
    (tree-sitter-hl-face:embedded        :foreground iris)

    ;; --- eglot / lsp-mode ---
    (eglot-highlight-symbol-face :background highlight-med :weight 'bold)
    (eglot-mode-line :foreground rose :weight 'bold)
    (eglot-diagnostic-tag-unnecessary-face :underline `(:style wave :color ,muted))
    (eglot-diagnostic-tag-deprecated-face  :strike-through t :foreground muted)
    (eglot-inlay-hint-face                 :foreground muted :background nil)
    (eglot-parameter-hint-face             :foreground iris  :background nil :slant 'italic)
    (eglot-type-hint-face                  :foreground foam  :background nil :slant 'italic)

    (lsp-face-highlight-read    :background highlight-med :weight 'bold)
    (lsp-face-highlight-write   :background highlight-high :weight 'bold)
    (lsp-face-highlight-textual :background highlight-low)
    (lsp-headerline-breadcrumb-path-face        :foreground subtle)
    (lsp-headerline-breadcrumb-path-error-face  :foreground love)
    (lsp-headerline-breadcrumb-symbols-face     :foreground rose :weight 'bold)
    (lsp-ui-sideline-symbol      :foreground muted :box nil)
    (lsp-ui-sideline-current-symbol :foreground rose :weight 'bold :box nil)
    (lsp-ui-sideline-code-action :foreground gold)
    (lsp-ui-doc-background       :background surface)
    (lsp-ui-doc-header           :background surface :foreground rose :weight 'bold)
    (lsp-ui-peek-filename        :foreground rose)
    (lsp-ui-peek-header          :background overlay :foreground text :weight 'bold)
    (lsp-ui-peek-selection       :background highlight-med)
    (lsp-ui-peek-list            :background surface)
    (lsp-ui-peek-peek            :background surface)
    (lsp-ui-peek-highlight       :foreground gold :background highlight-high)
    (lsp-signature-posframe      :background surface)

    ;; --- corfu ---
    (corfu-default     :background surface :foreground text)
    (corfu-current     :background highlight-med :foreground text :weight 'bold)
    (corfu-bar         :background highlight-high)
    (corfu-border      :background overlay)
    (corfu-annotations :foreground subtle :slant 'italic)
    (corfu-deprecated  :foreground muted :strike-through t)
    (corfu-echo        :foreground subtle)
    (corfu-popupinfo   :background surface :foreground text)

    ;; --- vertico / marginalia / orderless / consult / embark ---
    (vertico-current      :background highlight-med :foreground text :extend t :weight 'bold)
    (vertico-group-title  :foreground rose :weight 'bold)
    (vertico-group-separator :foreground overlay :strike-through t)
    (vertico-multiline    :foreground muted)

    (marginalia-key       :foreground gold)
    (marginalia-mode      :foreground iris)
    (marginalia-modified  :foreground love)
    (marginalia-file-priv-dir  :foreground iris :weight 'bold)
    (marginalia-file-priv-read :foreground gold)
    (marginalia-file-priv-write :foreground love)
    (marginalia-file-priv-exec :foreground foam)
    (marginalia-file-priv-no   :foreground muted)
    (marginalia-file-name      :foreground text)
    (marginalia-file-owner     :foreground subtle)
    (marginalia-date           :foreground rose)
    (marginalia-number         :foreground numbers)
    (marginalia-size           :foreground gold)
    (marginalia-documentation  :foreground subtle :slant 'italic)
    (marginalia-type           :foreground foam)
    (marginalia-value          :foreground subtle)
    (marginalia-symbol         :foreground iris)
    (marginalia-on             :foreground foam)
    (marginalia-off            :foreground muted)

    (orderless-match-face-0 :foreground rose :weight 'bold)
    (orderless-match-face-1 :foreground gold :weight 'bold)
    (orderless-match-face-2 :foreground foam :weight 'bold)
    (orderless-match-face-3 :foreground iris :weight 'bold)

    (consult-file           :foreground text)
    (consult-bookmark       :foreground iris)
    (consult-buffer         :foreground text)
    (consult-line-number    :foreground muted)
    (consult-line-number-prefix :foreground rose)
    (consult-line-number-wrapped :foreground gold)
    (consult-narrow-indicator :foreground gold :weight 'bold)
    (consult-async-running  :foreground gold)
    (consult-async-finished :foreground foam)
    (consult-async-failed   :foreground love)
    (consult-key            :foreground gold)
    (consult-imenu-prefix   :foreground iris)
    (consult-preview-line   :background highlight-low :extend t)
    (consult-preview-match  :background gold :foreground base)
    (consult-separator      :foreground overlay :strike-through t)

    (embark-keybinding      :foreground gold :weight 'bold)
    (embark-target          :background highlight-med :foreground text :weight 'bold)
    (embark-collect-marked  :background highlight-med)
    (embark-selected        :foreground rose :weight 'bold)

    ;; --- company / ivy / helm / swiper (legacy completion) ---
    (company-tooltip                  :background surface :foreground text)
    (company-tooltip-selection        :background highlight-med :foreground text)
    (company-tooltip-annotation       :foreground subtle :slant 'italic)
    (company-tooltip-annotation-selection :foreground text :slant 'italic)
    (company-tooltip-common           :foreground rose :weight 'bold)
    (company-tooltip-common-selection :foreground rose :weight 'bold)
    (company-scrollbar-bg             :background overlay)
    (company-scrollbar-fg             :background highlight-high)
    (company-preview                  :background nil :foreground muted)
    (company-preview-common           :background nil :foreground rose)
    (company-preview-search           :background gold :foreground base)
    (company-tooltip-search           :foreground gold :weight 'bold)
    (company-tooltip-search-selection :background gold :foreground base)

    (ivy-current-match :background highlight-med :distant-foreground fg)
    (ivy-minibuffer-match-face-1 :foreground subtle :weight 'bold)
    (ivy-minibuffer-match-face-2 :foreground rose   :weight 'bold)
    (ivy-minibuffer-match-face-3 :foreground gold   :weight 'bold)
    (ivy-minibuffer-match-face-4 :foreground foam   :weight 'bold)
    (ivy-minibuffer-match-highlight :foreground iris :weight 'bold)
    (ivy-posframe :background surface)
    (ivy-virtual :foreground muted :slant 'italic)
    (ivy-confirm-face :foreground foam)
    (ivy-match-required-face :foreground love)

    (helm-selection :background highlight-med :foreground text :weight 'bold)
    (helm-source-header :background overlay :foreground rose :weight 'bold)
    (helm-match :foreground rose :weight 'bold)
    (helm-visible-mark :background gold :foreground base)
    (helm-buffer-process :foreground foam)
    (helm-buffer-directory :foreground iris)

    (swiper-line-face       :background highlight-med :extend t)
    (swiper-background-match-face-1 :inherit 'lazy-highlight)
    (swiper-match-face-1    :inherit 'ivy-minibuffer-match-face-1)
    (swiper-match-face-2    :inherit 'ivy-minibuffer-match-face-2)
    (swiper-match-face-3    :inherit 'ivy-minibuffer-match-face-3)
    (swiper-match-face-4    :inherit 'ivy-minibuffer-match-face-4)

    ;; --- doom-modeline ---
    (doom-modeline-bar                  :background rose)
    (doom-modeline-bar-inactive         :background overlay)
    (doom-modeline-buffer-path          :foreground subtle)
    (doom-modeline-buffer-file          :foreground text :weight 'bold)
    (doom-modeline-buffer-modified      :foreground gold :weight 'bold)
    (doom-modeline-buffer-major-mode    :foreground rose :weight 'bold)
    (doom-modeline-buffer-minor-mode    :foreground subtle)
    (doom-modeline-project-parent-dir   :foreground iris :weight 'bold)
    (doom-modeline-project-dir          :foreground iris :weight 'bold)
    (doom-modeline-project-root-dir     :foreground iris)
    (doom-modeline-highlight            :foreground rose)
    (doom-modeline-panel                :background rose :foreground base)
    (doom-modeline-info                 :foreground foam)
    (doom-modeline-warning              :foreground gold)
    (doom-modeline-urgent               :foreground love :weight 'bold)
    (doom-modeline-debug                :foreground subtle :slant 'italic)
    (doom-modeline-lsp-success          :foreground foam)
    (doom-modeline-lsp-warning          :foreground gold)
    (doom-modeline-lsp-error            :foreground love)
    (doom-modeline-lsp-running          :foreground iris)
    (doom-modeline-input-method         :foreground iris)
    (doom-modeline-notification         :foreground gold :weight 'bold)
    (doom-modeline-unread-number        :foreground gold :weight 'bold)
    (doom-modeline-evil-emacs-state     :foreground iris :weight 'bold)
    (doom-modeline-evil-normal-state    :foreground foam)
    (doom-modeline-evil-insert-state    :foreground gold)
    (doom-modeline-evil-visual-state    :foreground rose)
    (doom-modeline-evil-replace-state   :foreground love)
    (doom-modeline-evil-operator-state  :foreground iris)
    (doom-modeline-evil-motion-state    :foreground foam)

    ;; --- solaire ---
    (solaire-default-face       :inherit 'default :background surface)
    (solaire-hl-line-face       :background overlay)
    (solaire-mode-line-face
     :inherit 'mode-line :background modeline-bg-alt
     :box (if modeline-pad `(:line-width ,modeline-pad :color ,modeline-bg-alt)))
    (solaire-mode-line-inactive-face
     :inherit 'mode-line-inactive :background modeline-bg-inactive-alt
     :box (if modeline-pad `(:line-width ,modeline-pad :color ,modeline-bg-inactive-alt)))

    ;; --- magit ---
    (magit-section-heading           :foreground iris :weight 'bold)
    (magit-section-heading-selection :foreground rose :weight 'bold)
    (magit-section-highlight         :background highlight-low :extend t)
    (magit-section-secondary-heading :foreground iris)
    (magit-diff-file-heading         :foreground text :weight 'bold)
    (magit-diff-file-heading-highlight :background highlight-low :foreground text :weight 'bold :extend t)
    (magit-diff-hunk-heading         :foreground subtle :background overlay :extend t)
    (magit-diff-hunk-heading-highlight :foreground text :background highlight-med :extend t)
    (magit-diff-hunk-region          :weight 'bold)
    (magit-diff-context              :foreground muted :extend t)
    (magit-diff-context-highlight    :foreground subtle :background highlight-low :extend t)
    (magit-diff-added                :foreground foam :background (doom-blend foam bg 0.10) :extend t)
    (magit-diff-added-highlight      :foreground foam :background (doom-blend foam bg 0.20) :extend t)
    (magit-diff-removed              :foreground love :background (doom-blend love bg 0.10) :extend t)
    (magit-diff-removed-highlight    :foreground love :background (doom-blend love bg 0.20) :extend t)
    (magit-diff-base                 :foreground gold :background (doom-blend gold bg 0.10) :extend t)
    (magit-diff-base-highlight       :foreground gold :background (doom-blend gold bg 0.20) :extend t)
    (magit-diff-lines-heading        :foreground gold :background highlight-med :extend t)
    (magit-diffstat-added            :foreground foam)
    (magit-diffstat-removed          :foreground love)
    (magit-branch-current            :foreground rose :weight 'bold :box t)
    (magit-branch-local              :foreground rose)
    (magit-branch-remote             :foreground foam)
    (magit-branch-remote-head        :foreground foam :weight 'bold)
    (magit-branch-upstream           :foreground iris)
    (magit-tag                       :foreground gold :weight 'bold)
    (magit-hash                      :foreground muted)
    (magit-log-author                :foreground iris)
    (magit-log-date                  :foreground subtle)
    (magit-log-graph                 :foreground muted)
    (magit-process-ok                :foreground foam :weight 'bold)
    (magit-process-ng                :foreground love :weight 'bold)
    (magit-signature-good            :foreground foam)
    (magit-signature-bad             :foreground love :weight 'bold)
    (magit-signature-untrusted       :foreground gold)
    (magit-signature-expired         :foreground gold)
    (magit-signature-revoked         :foreground love)
    (magit-cherry-equivalent         :foreground iris)
    (magit-cherry-unmatched          :foreground foam)
    (magit-bisect-good               :foreground foam)
    (magit-bisect-bad                :foreground love)
    (magit-bisect-skip               :foreground gold)
    (magit-blame-highlight           :foreground text :background highlight-low)
    (magit-blame-margin              :foreground subtle :background overlay)
    (magit-blame-heading             :foreground iris :background overlay :extend t)
    (magit-reflog-commit             :foreground foam)
    (magit-reflog-amend              :foreground iris)
    (magit-reflog-merge              :foreground foam)
    (magit-reflog-checkout           :foreground rose)
    (magit-reflog-reset              :foreground love)
    (magit-reflog-rebase             :foreground iris)
    (magit-reflog-cherry-pick        :foreground rose)
    (magit-reflog-remote             :foreground foam)
    (magit-reflog-other              :foreground subtle)
    (magit-keyword                   :foreground gold :weight 'bold)
    (magit-keyword-squash            :foreground rose :weight 'bold)
    (magit-popup-key                 :foreground gold :weight 'bold)
    (magit-popup-argument            :foreground iris)
    (magit-popup-disabled-argument   :foreground muted)
    (magit-filename                  :foreground rose)
    (magit-dimmed                    :foreground muted)

    ;; --- forge ---
    (forge-topic-open                :foreground foam :weight 'bold)
    (forge-topic-closed              :foreground iris)
    (forge-topic-merged              :foreground iris :weight 'bold)
    (forge-topic-unread              :foreground rose :weight 'bold)
    (forge-issue-open                :foreground foam :weight 'bold)
    (forge-issue-closed              :foreground iris)
    (forge-pullreq-open              :foreground foam :weight 'bold)
    (forge-pullreq-merged            :foreground iris :weight 'bold)
    (forge-pullreq-rejected          :foreground love)

    ;; --- diff / ediff / diff-hl / smerge ---
    (diff-added         :foreground foam :background (doom-blend foam bg 0.10) :extend t)
    (diff-removed       :foreground love :background (doom-blend love bg 0.10) :extend t)
    (diff-changed       :foreground rose :background (doom-blend rose bg 0.10) :extend t)
    (diff-refine-added  :foreground base :background foam :extend t)
    (diff-refine-removed :foreground base :background love :extend t)
    (diff-refine-changed :foreground base :background rose :extend t)
    (diff-context       :foreground muted :extend t)
    (diff-file-header   :foreground text :weight 'bold :extend t)
    (diff-hunk-header   :foreground subtle :background overlay :extend t)
    (diff-header        :foreground iris :weight 'bold :extend t)
    (diff-function      :foreground rose :extend t)
    (diff-indicator-added   :foreground foam)
    (diff-indicator-removed :foreground love)
    (diff-indicator-changed :foreground rose)

    (diff-hl-insert :foreground foam :background foam)
    (diff-hl-delete :foreground love :background love)
    (diff-hl-change :foreground rose :background rose)
    (diff-hl-margin-insert :foreground foam :background bg)
    (diff-hl-margin-delete :foreground love :background bg)
    (diff-hl-margin-change :foreground rose :background bg)

    (ediff-current-diff-A :background (doom-blend love bg 0.20) :foreground text :extend t)
    (ediff-current-diff-B :background (doom-blend foam bg 0.20) :foreground text :extend t)
    (ediff-current-diff-C :background (doom-blend gold bg 0.20) :foreground text :extend t)
    (ediff-current-diff-Ancestor :background (doom-blend iris bg 0.20) :foreground text :extend t)
    (ediff-fine-diff-A :background (doom-blend love bg 0.40) :foreground text :weight 'bold)
    (ediff-fine-diff-B :background (doom-blend foam bg 0.40) :foreground text :weight 'bold)
    (ediff-fine-diff-C :background (doom-blend gold bg 0.40) :foreground text :weight 'bold)
    (ediff-fine-diff-Ancestor :background (doom-blend iris bg 0.40) :foreground text :weight 'bold)
    (ediff-even-diff-A :background highlight-low :extend t)
    (ediff-even-diff-B :background highlight-low :extend t)
    (ediff-even-diff-C :background highlight-low :extend t)
    (ediff-even-diff-Ancestor :background highlight-low :extend t)
    (ediff-odd-diff-A  :background highlight-med :extend t)
    (ediff-odd-diff-B  :background highlight-med :extend t)
    (ediff-odd-diff-C  :background highlight-med :extend t)
    (ediff-odd-diff-Ancestor :background highlight-med :extend t)

    (smerge-base       :background (doom-blend iris bg 0.20) :extend t)
    (smerge-upper      :background (doom-blend love bg 0.20) :extend t)
    (smerge-lower      :background (doom-blend foam bg 0.20) :extend t)
    (smerge-markers    :background overlay :foreground iris :weight 'bold :extend t)
    (smerge-refined-added   :background (doom-blend foam bg 0.40) :extend t)
    (smerge-refined-removed :background (doom-blend love bg 0.40) :extend t)
    (smerge-refined-changed :background (doom-blend rose bg 0.40) :extend t)

    ;; --- flycheck / flymake ---
    (flycheck-error       :underline `(:style wave :color ,love))
    (flycheck-warning     :underline `(:style wave :color ,gold))
    (flycheck-info        :underline `(:style wave :color ,foam))
    (flycheck-fringe-error   :foreground love)
    (flycheck-fringe-warning :foreground gold)
    (flycheck-fringe-info    :foreground foam)
    (flycheck-posframe-background-face :background surface)
    (flycheck-posframe-error-face :foreground love :background surface)
    (flycheck-posframe-warning-face :foreground gold :background surface)
    (flycheck-posframe-info-face :foreground foam :background surface)

    (flymake-error    :underline `(:style wave :color ,love))
    (flymake-warning  :underline `(:style wave :color ,gold))
    (flymake-note     :underline `(:style wave :color ,foam))
    (flymake-error-echo   :foreground love)
    (flymake-warning-echo :foreground gold)
    (flymake-note-echo    :foreground foam)

    ;; --- hl-todo / rainbow-delimiters / highlight-numbers / highlight-quoted ---
    (hl-todo :foreground gold :weight 'bold :inverse-video t)

    (rainbow-delimiters-depth-1-face :foreground rose)
    (rainbow-delimiters-depth-2-face :foreground gold)
    (rainbow-delimiters-depth-3-face :foreground foam)
    (rainbow-delimiters-depth-4-face :foreground iris)
    (rainbow-delimiters-depth-5-face :foreground pine)
    (rainbow-delimiters-depth-6-face :foreground love)
    (rainbow-delimiters-depth-7-face :foreground rose)
    (rainbow-delimiters-depth-8-face :foreground gold)
    (rainbow-delimiters-depth-9-face :foreground foam)
    (rainbow-delimiters-mismatched-face :foreground base :background love :weight 'bold)
    (rainbow-delimiters-unmatched-face  :foreground base :background love :weight 'bold)

    (highlight-numbers-number :foreground numbers)
    (highlight-quoted-quote   :foreground operators)
    (highlight-quoted-symbol  :foreground iris)

    ;; --- which-key / avy / button / custom-button ---
    (which-key-key-face                   :foreground gold :weight 'bold)
    (which-key-group-description-face     :foreground rose :weight 'bold)
    (which-key-command-description-face   :foreground text)
    (which-key-local-map-description-face :foreground iris)
    (which-key-separator-face             :foreground muted)
    (which-key-note-face                  :foreground subtle :slant 'italic)
    (which-key-special-key-face           :foreground love :weight 'bold)
    (which-key-docstring-face             :foreground subtle :slant 'italic)

    (avy-lead-face            :foreground base :background gold :weight 'bold)
    (avy-lead-face-0          :foreground base :background rose :weight 'bold)
    (avy-lead-face-1          :foreground base :background foam :weight 'bold)
    (avy-lead-face-2          :foreground base :background iris :weight 'bold)
    (avy-background-face      :foreground muted)

    (button :inherit 'link)
    (custom-button         :background overlay      :foreground text :box `(:line-width 1 :color ,highlight-high))
    (custom-button-mouse   :background highlight-med :foreground text :box `(:line-width 1 :color ,rose))
    (custom-button-pressed :background highlight-high :foreground text :box `(:line-width 1 :color ,rose))

    ;; --- ansi-color (compile / eshell / term / vterm) ---
    (ansi-color-black          :foreground base   :background base)
    (ansi-color-red            :foreground love   :background love)
    (ansi-color-green          :foreground foam   :background foam)
    (ansi-color-yellow         :foreground gold   :background gold)
    (ansi-color-blue           :foreground pine   :background pine)
    (ansi-color-magenta        :foreground iris   :background iris)
    (ansi-color-cyan           :foreground foam   :background foam)
    (ansi-color-white          :foreground subtle :background subtle)
    (ansi-color-bright-black   :foreground muted  :background muted)
    (ansi-color-bright-red     :foreground love   :background love)
    (ansi-color-bright-green   :foreground foam   :background foam)
    (ansi-color-bright-yellow  :foreground gold   :background gold)
    (ansi-color-bright-blue    :foreground pine   :background pine)
    (ansi-color-bright-magenta :foreground iris   :background iris)
    (ansi-color-bright-cyan    :foreground foam   :background foam)
    (ansi-color-bright-white   :foreground text   :background text)

    ;; --- tab-bar / tab-line / centaur-tabs ---
    (tab-bar              :background surface :foreground subtle)
    (tab-bar-tab          :background base    :foreground rose :weight 'bold :box `(:line-width 3 :color ,base))
    (tab-bar-tab-inactive :background surface :foreground muted :box `(:line-width 3 :color ,surface))
    (tab-bar-tab-group-current  :background base :foreground iris :weight 'bold)
    (tab-bar-tab-group-inactive :background surface :foreground subtle)
    (tab-bar-tab-ungrouped      :background surface :foreground muted)

    (tab-line              :background surface :foreground subtle)
    (tab-line-tab          :background base    :foreground text)
    (tab-line-tab-current  :background base    :foreground rose :weight 'bold)
    (tab-line-tab-inactive :background surface :foreground muted)
    (tab-line-highlight    :background overlay :foreground text)

    (centaur-tabs-default              :background surface :foreground subtle)
    (centaur-tabs-selected             :background base    :foreground rose :weight 'bold)
    (centaur-tabs-unselected           :background surface :foreground muted)
    (centaur-tabs-selected-modified    :background base    :foreground gold :weight 'bold)
    (centaur-tabs-unselected-modified  :background surface :foreground gold)
    (centaur-tabs-active-bar-face      :background rose)
    (centaur-tabs-modified-marker-selected   :foreground gold)
    (centaur-tabs-modified-marker-unselected :foreground gold)

    ;; --- treemacs / dirvish / dired ---
    (treemacs-root-face            :foreground rose :weight 'bold :height 1.0)
    (treemacs-root-unreadable-face :foreground muted :strike-through t :weight 'bold)
    (treemacs-directory-face       :foreground iris)
    (treemacs-directory-collapsed-face :foreground iris)
    (treemacs-file-face            :foreground text)
    (treemacs-tags-face            :foreground subtle)
    (treemacs-fringe-indicator-face :foreground rose)
    (treemacs-git-added-face       :foreground foam)
    (treemacs-git-renamed-face     :foreground rose :slant 'italic)
    (treemacs-git-ignored-face     :foreground muted)
    (treemacs-git-untracked-face   :foreground gold)
    (treemacs-git-modified-face    :foreground rose)
    (treemacs-git-conflict-face    :foreground love :weight 'bold)
    (treemacs-on-success-pulse-face :foreground base :background foam :extend t)
    (treemacs-on-failure-pulse-face :foreground base :background love :extend t)
    (treemacs-marked-file-face     :foreground gold :weight 'bold)
    (treemacs-tag-face             :foreground subtle)

    (dirvish-hl-line               :background highlight-med :extend t)
    (dirvish-subtree-state-face    :foreground muted)
    (dirvish-git-commit-message-face :foreground subtle :slant 'italic)
    (dirvish-vc-needs-merge-face   :foreground love :weight 'bold)

    (dired-directory  :foreground iris :weight 'bold)
    (dired-symlink    :foreground foam :slant 'italic)
    (dired-marked     :foreground gold :weight 'bold)
    (dired-flagged    :foreground love :weight 'bold)
    (dired-header     :foreground rose :weight 'bold)
    (dired-perm-write :foreground gold)
    (dired-broken-symlink :foreground love :background highlight-low)
    (dired-warning    :foreground gold :weight 'bold)
    (dired-ignored    :foreground muted)
    (diredfl-dir-name       :foreground iris :weight 'bold)
    (diredfl-file-name      :foreground text)
    (diredfl-file-suffix    :foreground subtle)
    (diredfl-symlink        :foreground foam :slant 'italic)
    (diredfl-no-priv        :foreground muted)
    (diredfl-read-priv      :foreground gold)
    (diredfl-write-priv     :foreground love)
    (diredfl-exec-priv      :foreground foam)
    (diredfl-dir-priv       :foreground iris)
    (diredfl-link-priv      :foreground foam)
    (diredfl-number         :foreground numbers)
    (diredfl-date-time      :foreground rose)
    (diredfl-flag-mark      :foreground gold :weight 'bold)
    (diredfl-flag-mark-line :background highlight-low :extend t)
    (diredfl-deletion       :foreground love :weight 'bold)
    (diredfl-deletion-file-name :foreground love :strike-through t)

    ;; --- org / org-modern / org-roam ---
    (org-level-1 :foreground rose :weight 'bold :height 1.10)
    (org-level-2 :foreground foam :weight 'bold)
    (org-level-3 :foreground iris :weight 'bold)
    (org-level-4 :foreground gold)
    (org-level-5 :foreground foam)
    (org-level-6 :foreground iris)
    (org-level-7 :foreground rose)
    (org-level-8 :foreground love)
    (org-document-title :foreground rose :weight 'bold :height 1.2)
    (org-document-info  :foreground iris)
    (org-document-info-keyword :foreground muted)
    (org-meta-line :foreground muted :slant 'italic)
    (org-headline-done :foreground muted :strike-through t)
    (org-todo :foreground love :weight 'bold)
    (org-done :foreground foam :weight 'bold)
    (org-checkbox :foreground rose :weight 'bold)
    (org-checkbox-statistics-todo :foreground love :weight 'bold)
    (org-checkbox-statistics-done :foreground foam :weight 'bold)
    (org-priority :foreground gold :weight 'bold)
    (org-tag      :foreground iris :weight 'bold)
    (org-special-keyword :foreground subtle)
    (org-property-value :foreground subtle)
    (org-table    :foreground text :background (doom-blend overlay bg 0.40))
    (org-date     :foreground iris :underline t)
    (org-time-grid :foreground muted)
    (org-link     :foreground foam :underline t)
    (org-footnote :foreground foam :underline t)
    (org-quote    :foreground subtle :slant 'italic
                  :background (doom-blend overlay bg 0.50) :extend t)
    (org-verse    :foreground subtle :slant 'italic)
    (org-verbatim :foreground gold :background (doom-blend gold bg 0.10))
    (org-code     :foreground rose :background (doom-blend rose bg 0.10))
    (org-formula  :foreground iris)
    (org-list-dt  :foreground rose :weight 'bold)
    (org-ellipsis :foreground muted :underline nil)
    (org-block    :background (doom-blend overlay bg 0.50) :extend t)
    (org-block-background :background (doom-blend overlay bg 0.50))
    (org-block-begin-line :background (doom-blend overlay bg 0.80)
                          :foreground muted :slant 'italic :extend t)
    (org-block-end-line   :background (doom-blend overlay bg 0.80)
                          :foreground muted :slant 'italic :extend t)
    (org-drawer   :foreground muted)
    (org-warning  :foreground gold :weight 'bold)
    (org-archived :foreground muted :slant 'italic)
    (org-target   :foreground iris :underline t)
    (org-sexp-date :foreground iris)
    (org-scheduled :foreground foam)
    (org-scheduled-today :foreground foam :weight 'bold)
    (org-scheduled-previously :foreground gold :slant 'italic)
    (org-upcoming-deadline :foreground gold)
    (org-upcoming-distant-deadline :foreground subtle)
    (org-deadline-announce :foreground love :weight 'bold)
    (org-agenda-date :foreground iris :weight 'bold)
    (org-agenda-date-today :foreground rose :weight 'bold)
    (org-agenda-date-weekend :foreground love)
    (org-agenda-structure :foreground iris :weight 'bold)
    (org-agenda-current-time :foreground rose)
    (org-agenda-done :foreground muted :strike-through t)
    (org-agenda-dimmed-todo-face :foreground muted)
    (org-agenda-calendar-event :foreground text)
    (org-agenda-calendar-sexp  :foreground iris)
    (org-agenda-filter-category :foreground iris :weight 'bold)
    (org-agenda-filter-tags :foreground iris :weight 'bold)
    (org-mode-line-clock :foreground rose)
    (org-mode-line-clock-overrun :foreground love :weight 'bold)
    (org-column :background overlay)
    (org-column-title :background overlay :foreground rose :weight 'bold)
    (org-habit-clear-face   :background foam)
    (org-habit-clear-future-face :background (doom-blend foam bg 0.50))
    (org-habit-ready-face   :background gold)
    (org-habit-ready-future-face :background (doom-blend gold bg 0.50))
    (org-habit-alert-face   :background love)
    (org-habit-alert-future-face :background (doom-blend love bg 0.50))
    (org-habit-overdue-face :background love)
    (org-habit-overdue-future-face :background (doom-blend love bg 0.50))

    (org-modern-label :foreground base :background rose :weight 'bold)
    (org-modern-tag   :foreground base :background iris :weight 'bold)
    (org-modern-done  :foreground base :background foam :weight 'bold)
    (org-modern-todo  :foreground base :background love :weight 'bold)
    (org-modern-priority :foreground base :background gold :weight 'bold)
    (org-modern-date-active   :foreground base :background iris)
    (org-modern-date-inactive :foreground muted :background overlay)
    (org-modern-time-active   :foreground base :background iris)
    (org-modern-time-inactive :foreground muted :background overlay)
    (org-modern-statistics :foreground gold)
    (org-modern-progress-complete :background foam :foreground base)
    (org-modern-progress-incomplete :background overlay :foreground subtle)
    (org-modern-horizontal-rule :strike-through highlight-high)

    (org-roam-link :foreground rose :underline t)
    (org-roam-link-current :foreground rose :weight 'bold :underline t)
    (org-roam-title :foreground rose :weight 'bold)
    (org-roam-tag :foreground iris)
    (org-roam-olp :foreground muted)

    ;; --- markdown ---
    (markdown-markup-face          :foreground muted)
    (markdown-header-delimiter-face :foreground muted)
    (markdown-header-rule-face     :foreground muted)
    (markdown-header-face          :inherit 'bold :foreground rose)
    (markdown-header-face-1        :inherit 'markdown-header-face :height 1.10)
    (markdown-header-face-2        :inherit 'markdown-header-face :foreground foam)
    (markdown-header-face-3        :inherit 'markdown-header-face :foreground iris)
    (markdown-header-face-4        :inherit 'markdown-header-face :foreground gold)
    (markdown-header-face-5        :inherit 'markdown-header-face :foreground foam)
    (markdown-header-face-6        :inherit 'markdown-header-face :foreground iris)
    ((markdown-code-face &override) :background (doom-blend overlay bg 0.50))
    (markdown-pre-face             :foreground gold)
    (markdown-inline-code-face     :foreground rose :background (doom-blend rose bg 0.10))
    (markdown-link-face            :foreground foam :underline t)
    (markdown-url-face             :foreground muted :slant 'italic)
    (markdown-list-face            :foreground rose :weight 'bold)
    (markdown-bold-face            :foreground text :weight 'bold)
    (markdown-italic-face          :foreground text :slant 'italic)
    (markdown-blockquote-face      :foreground subtle :slant 'italic)
    (markdown-language-keyword-face :foreground iris :slant 'italic)
    (markdown-language-info-face   :foreground subtle :slant 'italic)
    (markdown-metadata-key-face    :foreground iris)
    (markdown-metadata-value-face  :foreground text)
    (markdown-table-face           :foreground text :background (doom-blend overlay bg 0.40))
    (markdown-gfm-checkbox-face    :foreground rose :weight 'bold)
    (markdown-html-tag-name-face   :foreground foam)
    (markdown-html-attr-name-face  :foreground iris)
    (markdown-html-tag-delimiter-face :foreground subtle)
    (markdown-html-entity-face     :foreground iris)
    (markdown-line-break-face      :underline highlight-high)
    (markdown-reference-face       :foreground foam :underline t)

    ;; --- web-mode ---
    (web-mode-html-tag-face         :foreground foam)
    (web-mode-html-tag-bracket-face :foreground subtle)
    (web-mode-html-attr-name-face   :foreground iris)
    (web-mode-html-attr-value-face  :foreground gold)
    (web-mode-css-property-name-face :foreground iris)
    (web-mode-css-selector-face     :foreground rose)
    (web-mode-css-pseudo-class-face :foreground foam :slant 'italic)
    (web-mode-css-at-rule-face      :foreground iris)
    (web-mode-css-string-face       :foreground gold)
    (web-mode-css-color-face        :foreground gold)
    (web-mode-keyword-face          :foreground keywords :weight 'bold)
    (web-mode-builtin-face          :foreground builtin :slant 'italic)
    (web-mode-function-name-face    :foreground functions)
    (web-mode-variable-name-face    :foreground variables)
    (web-mode-string-face           :foreground strings)
    (web-mode-comment-face          :foreground muted :slant 'italic)
    (web-mode-symbol-face           :foreground iris)
    (web-mode-doctype-face          :foreground muted :slant 'italic)

    ;; --- css / scss ---
    (css-property             :foreground iris)
    (css-proprietary-property :foreground iris)
    (css-selector             :foreground rose)

    ;; --- widget ---
    (widget-field             :foreground text :background overlay)
    (widget-single-line-field :foreground text :background overlay)
    (widget-button            :foreground rose :weight 'bold)
    (widget-button-pressed    :foreground gold :weight 'bold)
    (widget-documentation     :foreground subtle :slant 'italic)
    (widget-inactive          :foreground muted))
  "Face overrides shared by every Rosé Pine variant.
All entries reference palette role names (rose, gold, foam, pine,
iris, love, text, subtle, muted, base, surface, overlay,
highlight-low, highlight-med, highlight-high, and the doom-themes
spectrum bg/fg/base0..base8/grey/red/orange/green/yellow/blue/
dark-blue/magenta/violet/cyan/dark-cyan/teal).  Each theme file
binds those names to its variant-specific colors before passing
this list to `def-doom-theme'.")

(defmacro doom-rose-pine--def-theme (name docstring palette)
  "Define a Rosé Pine theme variant.
NAME is the theme symbol, DOCSTRING the description, PALETTE the
variable bindings (passed as `def-doom-theme's defs)."
  `(def-doom-theme ,name ,docstring
     ,palette
     ,doom-rose-pine--face-spec))

;;;###autoload
(when load-file-name
  (add-to-list 'custom-theme-load-path
               (file-name-directory load-file-name)))

(provide 'doom-rose-pine-common)
;;; doom-rose-pine-common.el ends here
